language: java

jdk:
  - oraclejdk8
  - oraclejdk7

deploy:
  provider: releases
  api_key: 1a987911e1906746704438a841df72fcc5e4b363
  file: build/libs/RobotProject.jar
  skip_cleanup: true
  on:
      tags: true
